version: '3'

volumes:
  tmp-data:

services:
  app:
    image: zsbing84/circleci-test
    volumes:
      - .:/webapp
      - tmp-data:/webapp/tmp
    environment:
      - RAILS_ENV=production
      - tmp-data:/webapp/tmp
    command: rails s
  web:
    image: zsbing84/nginx-test
    volumes:
      - tmp-data:/webapp/tmp
      - ./containers/nginx/log:/var/log/nginx/
    ports:
      - 80:80
    depends_on:
      - app
